---
title: ProjecTILs case studies
date: "`r Sys.Date()`"
author: "M. Andreatta and S. Carmona"
output:
  rmdformats::readthedown:
    self-contained: true
    highlight: haddock
    thumbnails: false
    css: styles.css
knit: (function(input_file, encoding) {
  out_dir <- 'docs';
  rmarkdown::render(input_file, encoding=encoding, output_file=file.path(dirname(input_file), out_dir, 'index.html'))})
---

```{r setup, echo=FALSE, cache=FALSE}
#install.packages("rmdformats")
#Template markdown setup
library(knitr)
library(rmdformats)

## Global options
options(max.print="75")
opts_chunk$set(echo=TRUE,
	             cache=TRUE,
               prompt=FALSE,
               tidy=FALSE,
               comment=NA,
               message=FALSE,
               warning=FALSE,
               dev = 'png')
opts_knit$set(width=75)

```

We will be posting here interesting/instructive case studies of single-cell data analysis using [ProjecTILs](https://www.biorxiv.org/content/10.1101/2020.06.23.166546v1). Read the notebooks linked below, or get the source code to run it on your machine from the [GitHub repository](https://github.com/carmonalab/ProjecTILs_CaseStudies)

# 1. [MC38 TILs with clonotype analysis](Xiong19_TCR.html)

In [this case study](Xiong19_TCR.html), we build an integrated scRNA-seq analysis workflow to interpret the **transcriptional** (scRNA-seq) and **clonal structure** (scTCR-seq) of tumor-infiltrating T cells in MC38 colon adenocarcinoma.

# 2. [Project human data on mouse TIL atlas](SadeFeldman_ortho.html)

Exploiting the ortholog mapping functionality of ProjecTILs, we project scRNA-seq from melanoma patients (Sade-Feldman, 2018) onto a mouse reference atlas, to interpret T cell phenotype differences between responders and non-responders to checkpoint blockade therapy.

# 3. [T cell diversity across multiple tissues](Sandu_LCMV.html)

Apply ProjecTILs to investigate transcriptional profiles of CD8 T cells in chronic infection from **six different tissues.**

# 4. [Exhausted CD8 T cells are associated with ICB responsiveness in breast cancer](Bassez_BC.html)

Re-analysis of the dataset by Bassez et al. *Nat Med* (2020) of breast cancer patients treated with anti-PD-1 therapy

# 5. [Memory phenotypes of CD4+ T cells after acute infection](Kunzli.html)

A case study of projection of virus-specific CD4+ T cells in late acute infection.

# 6. [Detecting novel/unrepresented cell states](novelstate.html)

Projection of tumor-specific T cells on a viral reference, illustrating how one can interpret subtypes not represented in the reference.

# 7. [Effect of anti-PD-L1 therapy on CD4+ T cells](Snell.html)

Analysing the transcriptional phenotype of CD4+ T cells in chronic infection after treatment with an anti-PD-L1 antibody.

# 8. [Exploring dendritic cell diversity in human spleen](Brown2019_humanDC.html)

Projection of human DCs from spleen from the study of Brown et al. *Cell* (2019)
